In [1]:
import pandas as pd

In [2]:
targ_eval = pd.read_csv("Application_Scorecard_Full_Table__25_Vars_.csv")
targ_eval.head()

cust_id application_date  age  monthly_income employment_type  \
0  CUST000001       2022-04-13   50         15146.0        SALARIED   
1  CUST000002       2022-12-15   30          9762.0        SALARIED   
2  CUST000003       2022-09-28   59          3000.0        SALARIED   
3  CUST000004       2022-04-17   48         17437.0   SELF-EMPLOYED   
4  CUST000005       2022-03-13   56         15042.0        SALARIED   

  residential_status  credit_limit  debt_to_income  bureau_score  inq_6m  ...  \
0               RENT         15000            0.67         584.0       2  ...   
1                OWN          5000            0.27         761.0       1  ...   
2               RENT         15000            0.25         664.0       2  ...   
3               RENT         20000            0.38         810.0       1  ...   
4                OWN          5000            0.28         708.0       2  ...   

   emi_to_income_ratio  new_trades_3m  utilization_ratio  thin_file_flag  \
0                 0.35              2               0.15               1   
1                 0.20              2               0.02               0   
2                 0.16              2               0.68               0   
3                 0.35              2               0.30               0   
4                 0.19              3               0.38               0   

   ptp_flag_bureau  education_level  gender  marital_status  risk_region_flag  \
0                0          MASTERS    MALE         MARRIED                 0   
1                1        BACHELORS  FEMALE         MARRIED                 0   
2                0            OTHER    MALE          SINGLE                 0   
3                0          MASTERS  FEMALE          SINGLE                 1   
4                0          MASTERS    MALE         MARRIED                 0   

   channel_code  
0        ONLINE  
1        ONLINE  
2        ONLINE  
3        BRANCH  
4        BRANCH  

[5 rows x 26 columns]

In [3]:
targ_eval['delinq_12m'].unique()

array([1, 0, 2], dtype=int64)

In [1]:
import numpy as np

In [29]:
n_assets = 2
n_sim = 3

In [30]:
returns = np.random.randn(n_assets, n_sim)
returns

array([[-0.43534569,  0.44648301, -0.50749615],
       [ 0.7092801 , -0.81150358,  1.79578368]])

In [38]:
returns.T

array([[-0.43534569,  0.7092801 ],
       [ 0.44648301, -0.81150358],
       [-0.50749615,  1.79578368]])

In [31]:
rand = np.random.randn(n_assets)
rand

array([0.22002331, 0.56756174])

In [32]:
sum(rand)

0.787585041189788

In [33]:
weights = rand/sum(rand)
weights

array([0.27936451, 0.72063549])

In [40]:
weights.shape

(2,)

In [35]:
rets = np.mean(returns, axis=1)
rets

array([-0.16545295,  0.56452007])

In [36]:
returns.T

array([[-0.43534569,  0.7092801 ],
       [ 0.44648301, -0.81150358],
       [-0.50749615,  1.79578368]])